### ISSUE TITLE
Hyperlinks are Displayed instead of Tags in Tweets

### ISSUE THREAD

**Issue by VibhuKesar** [fossasia/2016.fossasia.org#109]
![screenshot 22](https://cloud.githubusercontent.com/assets/20054569/16695801/5e359b76-455f-11e6-8718-150c1d3fefdf.png)

**Comment by jigyasa-grover** [comment]
@VibhuKesar Go ahead and send in a fix ..

**Comment by mariobehling** [comment]
This issue is related to loklak: http://loklak.org So, closing it here.
