### ISSUE TITLE
Add links to speakers' profile

### ISSUE THREAD

**Issue by Ploypiti** [fossasia/2016.fossasia.org#126]
1. **Colin Charles** | https://www.instagram.com/bytebot/
2. **Anisha Narang** | https://github.com/anarang
3. **Syah Dwi Prihatmoko** | https://github.com/sdmoko
4. **Alexander Bezzubov** | https://www.linkedin.com/in/alexanderbzz/
5. **Kukuh Syafaat** | https://www.instagram.com/cho2mlhc/
6. **Menghsuan Tsai** | https://www.linkedin.com/in/meng-hsuan-tsai-306a5199/
7. **Dilum Navanjana** | https://www.instagram.com/dilumn/
8. **Akhil Pandey** | https://www.instagram.com/akhil__pandey/

*edited*

**Comment by abishekvashok** [comment]
@Ploypiti since it's closed pls close this.
Just use this syntax in the pr description to automatically close the issue on pr merge:
`Fixes #issueno`
