### ISSUE TITLE
Add missing speaker links

### ISSUE THREAD

**Issue by abishekvashok** [fossasia/2016.fossasia.org#134]
Add fb links of:
- [ ] Chinmay Pendharkar https://www.facebook.com/chinpen
- [ ] Micheal Christen https://www.facebook.com/michael.christen
- [ ] Praveen Patil https://www.facebook.com/praveenpatil103
- [ ] Marco Gutierrez https://www.facebook.com/marco.a.gutierrez
- [ ] Sudheesh Singanamalla https://www.facebook.com/sudheesh001
- [ ] Amit Kumar Jha https://www.facebook.com/iaktech
- [ ] Stephan Wissel https://www.facebook.com/stephan.wissel
- [ ] Soares Chen https://www.facebook.com/soareschen

Working on it

**Comment by nzec** [comment]
You working on it?

**Comment by abishekvashok** [comment]
@duttaditya18 yes
