### ISSUE TITLE
Generate simple html schedule from Google doc like at OpenTechSummit

### ISSUE THREAD

**Issue by mariobehling** [fossasia/2016.fossasia.org#16]
At OpenTechSummit we used a programm.html to generate the schedule from a Google doc. Please adapt the progamm.html to work with the FOSSASIA schedule.

Links
- Google doc https://docs.google.com/spreadsheets/d/1QeAyxbEc1fP9h5_kGQh-EVrx5RaYgbKFJBE9wUjIdvc
- Html: https://github.com/fossasia/2016.fossasia.org/blob/gh-pages/schedule/index.html
- Online: http://2016.fossasia.org/schedule/

The original is here: 
- http://2015.opentechsummit.net/programm.html
- https://github.com/OpenTechSummit/2015.opentechsummit.net/blob/gh-pages/programm.html

**Comment by joerx** [comment]
Added schedule. Some tweaks are still required, but we can tackle those as separate issues.

**Comment by mariobehling** [comment]
Ok, looks great already. Let me go through it a bit and then we can release.
