### ISSUE TITLE
Web Push notifications for event updates.

### ISSUE THREAD

**Issue by batraabhishek** [fossasia/2016.fossasia.org#2]
Hi All,
We can use some service like pushcrew.com to provide real time browser based push notifications during the event/conf. All we have to include is a small snippet of javascript code in the html file. 

What say? Will be useful i guess.

**Comment by mariobehling** [comment]
Yes, very good idea. However, is there a simple solution to do this ourselves instead of using this service? Or could we use a twitter stream (but using the loklak API)?
