### ISSUE TITLE
Use github profile image for speakers without images

### ISSUE THREAD

**Issue by aviaryan** [fossasia/2016.fossasia.org#25]
In context to #23 and #24, if a speaker doesn't have an image, we can use his github profile image instead. It can be trivially build from GitHub username.

```
https://avatars2.githubusercontent.com/USERNAME
```

example - https://avatars2.githubusercontent.com/aviaryan

**Comment by aviaryan** [comment]
@sudheesh001 @daminisatya @joerx What do you think of this ?
I am aware that some speakers may have not set their github profile images. In that case we would be stuck with github _random squares_ image. But that should not be the case most of the times.

**Comment by daminisatya** [comment]
@aviaryan I extracted the github images for those who dint provide a photo. Those default images are those speakers who dint include any of their social networking links. But still i will go through it once again.

**Comment by aviaryan** [comment]
@daminisatya I think you have missed that. As far as I can see, you aren't using github images in PR #24 .

@mariobehling Should I download github images of speakers who haven't provided their image url and send a PR ?

**Comment by daminisatya** [comment]
#24

**Comment by sudheesh001** [comment]
I think most of the images have already been added, i've seen the information of github in each speaker object in the given json, they're inconsitent with some being full urls and some being just the usernames. I think @daminisatya has pushed most of the files in the PR proposed

**Comment by daminisatya** [comment]
#24 Check here, I updated the PR

**Comment by aviaryan** [comment]
@daminisatya Great :+1: . Thanks . I will close this issue now.
