### ISSUE TITLE
Loading screen on schedule page

### ISSUE THREAD

**Issue by joerx** [fossasia/2016.fossasia.org#26]
Schedule page is loading data via Ajax, leading to a noticeable delay (during which the page is just blank) - we should add a small loader animation instead.

**Comment by SilentFlame** [comment]
@joerx 
can be closed if PR #59 does the work.

**Comment by SilentFlame** [comment]
@joerx have a look at PR #60

**Comment by joerx** [comment]
Not fixed. See my comment on #60

**Comment by jigyasa-grover** [comment]
@joerx Okay, cool.
Have the changes been reverted ?

**Comment by joerx** [comment]
yes

**Comment by jigyasa-grover** [comment]
:+1:

**Comment by SilentFlame** [comment]
@joerx so exacltly when do we need to hide the loader image.
1. when the data is fetched.?
2. when data is parsed.?

I think the later is what exactly you were mentioning in the comment provided in #59.
tell me and I'll add that there. :smiley:

**Comment by joerx** [comment]
It's not about "when" but "how" - check the bottom part of main.js,
particularly the part that says `store.on()`.

On Fri, Mar 11, 2016 at 10:21 PM, Vinay Singh notifications@github.com
wrote:

> @joerx https://github.com/joerx so exacltly when do we need to hide the
> loader image.
> 1. when the data is fetched.?
> 2. when data is parsed.?
> 
> I think the later is what exactly you were mentioning in the comment
> provided in #59 https://github.com/fossasia/2016.fossasia.org/pull/59.
> tell me and I'll add that there. [image: :smiley:]
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/fossasia/2016.fossasia.org/issues/26#issuecomment-195384268
> .

## 

_joerg henning /_ software developer & consultant
mobile: +65 9038 9670
twitter: @JoergHenning https://twitter.com/JoergHenning

**Comment by SilentFlame** [comment]
@joerx I didn't get you here, can't we just make the loader stay there until the whole data is fetched and parsed and then as the data loads we should hide the loader.

**Comment by joerx** [comment]
Which part of "look at [the bottom of main.js](https://github.com/fossasia/2016.fossasia.org/blob/gh-pages/schedule/main.js#L272)" are you having trouble with?

**Comment by SilentFlame** [comment]
I mean what exactly we need here to do with the data event?
embed the loader into the event? as when the event ends it stops the loader image.
or something else?

**Comment by joerx** [comment]
Schedule has been converted to static page (see #64), this won't be necessary anymore.
