### ISSUE TITLE
Match design of schedule page

### ISSUE THREAD

**Issue by joerx** [fossasia/2016.fossasia.org#27]
Schedule page right now uses Bootstrap default style, which is pretty unexciting. However, it's clean & responsive. Please sensibly adjust the Bootstrap theme to match the main page more closely.

**Comment by daminisatya** [comment]
@joerx Working on it !

**Comment by mariobehling** [comment]
@daminisatya Could you make a quick change of the time buttons of blue to FOSSASIA red, please? And make a PR. Please release early and often.

**Comment by daminisatya** [comment]
@mariobehling sure.

**Comment by mariobehling** [comment]
@daminisatya If you have time provide a sample design as an image here. So, we can get an idea where you are heading. Also, please take this into account: https://github.com/fossasia/2016.fossasia.org/issues/28

**Comment by daminisatya** [comment]
@mariobehling Sure ! Will work on it after pushing the speaker's PR, I'm almost done with the speaker's list.

**Comment by joerx** [comment]
Please don't include the theme css for the main page. It breaks the hamburger menu on mobile (see #35) - match fonts and colours, don't touch anything else.

**Comment by joerx** [comment]
Done
