### ISSUE TITLE
Schedule Page: Enable expansion on click providing more info

### ISSUE THREAD

**Issue by mariobehling** [fossasia/2016.fossasia.org#28]
In the normal schedule view, sessions can look like that:
![screenshot from 2016-03-06 17 18 02-1](https://cloud.githubusercontent.com/assets/1583873/13553368/20cf07c6-e3c2-11e5-8574-7c41f0f470fc.png)
- [x] Please change blue to FOSSASIA red

In the expanded view, please add 
- [x] abstract info
- [ ] speaker bio
- [ ] below speaker bio simple black icons of web (world icon) github, fb, twitter with links to speaker

Simple draft:
![screenshot from 2016-03-06 17 18 02](https://cloud.githubusercontent.com/assets/1583873/13553376/60d1b012-e3c2-11e5-8354-06df3198c796.png)

**Comment by AmayAgrawal** [comment]
I think that this can work like the one we did in the open-event webapp.But I m not getting that how to run it locally on  my machine.

**Comment by daminisatya** [comment]
@AmayAgrawal You cant see the result locally since the file looks something like this file:///, so the browser doesnt allow you to do XHR requests on a local file. Either run it on caddy server or xampp. It works fine.

**Comment by AmayAgrawal** [comment]
Ok thanks for the information

**Comment by mariobehling** [comment]
@AmayAgrawal http://fossasia-slack.herokuapp.com Please join channel app-dev. Cheer.

**Comment by joerx** [comment]
@AmayAgrawal: Easiest way to run locally: https://caddyserver.com/ - Caddyfile is provided inside /schedule folder.

**Comment by joerx** [comment]
Done
