### ISSUE TITLE
No Readme.md or documentation provided.

### ISSUE THREAD

**Issue by vicky002** [fossasia/2016.fossasia.org#3]
Hi, 

I wanted to is this site is live? If yes then it would be good if you can mention the URL somewhere. 

also there is no documentation or Wiki page for contributing to the repo.

**Comment by jig08** [comment]
Yep, it is  http://2016.fossasia.org/

**Comment by mariobehling** [comment]
This is just a simple website, not a software project. So, we do not plan to set up a wiki or documentation.
