### ISSUE TITLE
Change details on schedule page

### ISSUE THREAD

**Issue by mariobehling** [fossasia/2016.fossasia.org#30]
This is obvious, so:
- [x] take out "Speaker"
- [x] take out "Type"

![screenshot from 2016-03-06 19 28 20](https://cloud.githubusercontent.com/assets/1583873/13553847/c6538974-e3d1-11e5-8278-ad20fa7acd86.png)
- [x] Add Organization, behind speaker in brakets e.g. Lennart Poettering (RedHat)

**Comment by SilentFlame** [comment]
@mariobehling @jig08 
going through page's source code I found that there is only one call to `sessions.json` in the `main.js` file.
So either we have to add the `organisation` field to the `sessions.json` file in the **speakers** section or we need to link the `speakers.json` file with the main.js.
What do you say?

**Comment by joerx** [comment]
Added org. Can be closed
