### ISSUE TITLE
Hamburger menu for switching days not working on mobile

### ISSUE THREAD

**Issue by zionsg** [fossasia/2016.fossasia.org#35]
Was unable to switch between the 3 days in the schedule while viewing it on mobile (iPhone 5S). Only saw the buttons for the 3 days when viewing on desktop.

**Comment by joerx** [comment]
Fixed by removing the lava theme from the schedule page. Buttons are still red, but the rest of the theme does not match now. I'll open a new issue for that.

**Comment by joerx** [comment]
d81c980a9e5a8b84f76a4cb70c8ef5d0940d0e61
