### ISSUE TITLE
Type of talks not displayed on 18th march 

### ISSUE THREAD

**Issue by mananwason** [fossasia/2016.fossasia.org#48]
Apart from Opentech and Opentech Workshops, type of all others talks is not displayed even though the json file has this detail.
<img width="1238" alt="screen shot 2016-03-07 at 9 36 34 pm" src="https://cloud.githubusercontent.com/assets/10570249/13575027/c0f84718-e4ac-11e5-9523-1adb62793479.png">
<img width="1222" alt="screen shot 2016-03-07 at 9 36 49 pm" src="https://cloud.githubusercontent.com/assets/10570249/13575028/c0fcb488-e4ac-11e5-8055-29ceded7ce5c.png">

**Comment by sreejakshetty** [comment]
@mananwason 
I have checked every name in json file is displayed here . If still there is any bug please tell me I would like to work on it . Thank You 
![screenshot from 2016-03-08 21 10 55](https://cloud.githubusercontent.com/assets/14835922/13606534/45fba08e-e572-11e5-85ca-4c42699701fb.png)

**Comment by mananwason** [comment]
@kamishettysreeja25 what do you mean that you have checked every name in json file?
 The problem is with the session type not displaying on the website even though it is present in the json file.

**Comment by kamishettysreeja25** [comment]
@mananwason  Okay I thought it is the names which are  not displayed . Okay I got it .

**Comment by brainzest** [comment]
Fixed. https://github.com/brainzest/2016.fossasia.org/commit/36334f919011251f54ee2f11bee79936a5828934

**Comment by mariobehling** [comment]
Issue is solved. Thanks.
