### ISSUE TITLE
Error in Timings Day 0 ?

### ISSUE THREAD

**Issue by sudheesh001** [fossasia/2016.fossasia.org#5]
@mariobehling Is this 2PM by any chance instead of 2AM ? If this is a typo, we can fix it, or else please feel free to close this issue.
https://github.com/fossasia/2016.fossasia.org/blob/gh-pages/index.html#L526

**Comment by isuruAb** [comment]
Here the exact place 
![untitled-1](https://cloud.githubusercontent.com/assets/7692626/12371414/e0b2ca46-bc58-11e5-8744-5c90f29910a1.png)

**Comment by mariobehling** [comment]
Ahh, Thank you. Fixed it.
