### ISSUE TITLE
Implement a submenu for each day with the tracks

### ISSUE THREAD

**Issue by mariobehling** [fossasia/2016.fossasia.org#62]
The intended menu items should include all tracks for each day e.g.
- Friday, March 18
  - OpenTech and IoT
  - Tech Kids I
  - Tech Kids II
  - Hardware and IoT
  - Big Data/Open Data
  - DevOps
  - Internet, Society, Community
  - Exhibition
- Saturday March 19
  - OpenTech and IoT
  - OpenTech Workshops
  - Tech Kids I
  - Tech Kids II
  - Tech Kids III
  - Hardware and IoT
  - DevOps
  - WebTech
  - Python
  - Big Data/Open Data
  - Databases
  - Exhibition 
- Sunday...
  - ...

**Comment by joerx** [comment]
Please open the page on a mobile device and re-think your approach. The menu is collapsed into a single button - a hierarchy would not work well in that case. With UX in mind, a single dropdown or quick-links for tracks on top of the page would be a better solution.

**Comment by mariobehling** [comment]
Please check on the main site http://2016.fossasia.org and check how the mobile site is implemented here. You can just copy the code as well and implement it as another menu here. It also works with submenus.

**Comment by SilentFlame** [comment]
@mariobehling Is this is what exactly you wanted to be done here.?
![18th_01](https://cloud.githubusercontent.com/assets/9693795/13716791/4a6af05a-e803-11e5-8d24-92f108ae8d82.png)
![19th_02](https://cloud.githubusercontent.com/assets/9693795/13716792/4a7a32cc-e803-11e5-8a11-1a7c2b71f587.png)
![20th](https://cloud.githubusercontent.com/assets/9693795/13716793/4a7d1fbe-e803-11e5-9d21-79a50a11a902.png)
have a look.

**Comment by mariobehling** [comment]
did you have a look at the main page?

![screenshot from 2016-03-12 09 37 24](https://cloud.githubusercontent.com/assets/1583873/13719795/443ce7be-e836-11e5-8693-d9a162743890.png)

Could you also please give links to a github page with the features instead of screenshots?
- [ ] implement menu as main menu on http://2016.fossasia.org (but with style suitable for schedule, e.g. transparent overlay does not work)
- [ ] implement mobile menu in the same way as on main page
- [ ] re-use existing theme CSS for menu

**Comment by mariobehling** [comment]
Here is a rough idea, what we need.
![screenshot from 2016-03-12 10 44 13](https://cloud.githubusercontent.com/assets/1583873/13720307/3b5c27d6-e840-11e5-98d6-19ebc4f25fe3.png)

**Comment by SilentFlame** [comment]
@mariobehling  does the list in the sub-menu needed to have links?
or just a static list of all the tracks would do the work?

**Comment by jigyasa-grover** [comment]
@mariobehling @SilentFlame I believe links would be more useful.
But for the time being, lets have the sub-menus implemented first ?

**Comment by SilentFlame** [comment]
@jig08 but since the page is itself having the list of all the things so this doesn't make sense here I guess.

**Comment by jigyasa-grover** [comment]
Easy access/navigation, maybe ?

**Comment by SilentFlame** [comment]
ohk you mean on clicking on them we should go down to those track I guess. :smiley: 
ya It make sense.

**Comment by jigyasa-grover** [comment]
Exactly !

**Comment by SilentFlame** [comment]
ohk trying that :smiley: 
@jig08  are you on slack or IRC? need to ask some things.

**Comment by jigyasa-grover** [comment]
Yes, on _FOSSASIA Slack_ `#app-dev` channel as `@jigyasa`

**Comment by joerx** [comment]
Fixed via b865f262eb683047c148b270a68b64f816ffb2e6. @mariobehling please review

**Comment by mariobehling** [comment]
@joerx Thanks for the update.

Next steps that would be good:
- [x] Order of tracks according to spreadsheet versioning doc
- [x] Make anchor link to heading (at the moment the link goes to the start date instead of the heading)

**Comment by SilentFlame** [comment]
@mariobehling need clarification regarding point 1.
I guess point 2 is done as it appears for me now.
point 3 unable to understand.
point 4 again done.
