### ISSUE TITLE
cut out json loading?

### ISSUE THREAD

**Issue by rctay** [fossasia/2016.fossasia.org#64]
Hi everyone, I came here for #28, and saw that `/schedule`, and in general the whole deployment and site hosting revolves around github pages static files. Would there be any interest in having a deployment step, running of code in a separate staging branch, say, `master`, and generate the complete schedule page in json, using the json input, so that the final deployed result doesn't load json anymore?

We could automate it with Travis, which integrates with github very well, and free, so newbies would not have to do a thing, and it would be transparent also (no one needs to login somewhere every few hours to run some command to deploy whenever there some commits/merges).

**Comment by joerx** [comment]
I don't see why loading the schedule data as JSON is a problem. It seems to work great so far.
- Schedule data is parsed out of a Google sheet and consumed by multiple clients
- Data needs to be updated regardless, as schedule changes sometimes
- JSON is loaded in background to reduce page load time
- Having structured data allows filtering schedule page on the fly (currently by day, filter by track/title also possible)

**Comment by joerx** [comment]
@rctay - had a quick chat with @mariobehling about this. We'll follow this approach after all. I'm about to get started on this. My idea is to simply use mustache.js to render the html page. Please let me know if you'd like to help or have any suggestions.

**Comment by hpdang** [comment]
+1 @rctay can do this in one hour right :D?

**Comment by joerx** [comment]
Done, please review

**Comment by rctay** [comment]
I take it that `schedule/index.html` is the final generated result from mustache? Do you have the original source template?

**Comment by championswimmer** [comment]
@joerx Yeah would like to see the mustache template and the script to generate it. I am working on enabling search and speaker details on the index.html page

**Comment by mariobehling** [comment]
@rctay @championswimmer Please have a look here: https://github.com/fossasia/open-event-scraper

**Comment by joerx** [comment]
@mariobehling - Can we close this issue now?

**Comment by mariobehling** [comment]
yeah, think so.
