### ISSUE TITLE
Broken links for Topics

### ISSUE THREAD

**Issue by mananwason** [fossasia/2016.fossasia.org#7]
The website has these broken links for images under topics.
<img width="1440" alt="screen shot 2016-01-15 at 12 22 54 pm" src="https://cloud.githubusercontent.com/assets/10570249/12347330/e8d33bec-bb82-11e5-94a1-254d334df953.png">

**Comment by SilentFlame** [comment]
@mananwason 
I am unable to understand the problem as when I visited the page it seems all ok.
can you please elaborate on the issue as I would like to fix this.

This is the view I got.
![foss](https://cloud.githubusercontent.com/assets/9693795/12364054/68df12d8-bbf2-11e5-8b90-29adf56e27dd.png)

**Comment by isuruAb** [comment]
i think this one is already fixed  ?

**Comment by jigyasa-grover** [comment]
Seems fine to me as well.

![screenshot from 2016-01-16 13 17 00](https://cloud.githubusercontent.com/assets/9291400/12371281/ac4e9cf8-bc53-11e5-9ccd-402a66e608e1.png)

**Comment by SilentFlame** [comment]
Then, would be better to close the issue.

**Comment by mananwason** [comment]
@SilentFlame Yes. Closing it !

**Comment by mananwason** [comment]
Closed via 2327b1defa00b0be7e0812c3b77f9b56e1ab59e7
