### ISSUE TITLE
Add social media icons/links to schedule page

### ISSUE THREAD

**Issue by mariobehling** [fossasia/2016.fossasia.org#72]
- [ ] YouTube Channel
- [ ] Github
- [ ] Twitter
- [ ] Facebook

See as an example here on the top right.

![screenshot from 2016-03-12 10 44 13](https://cloud.githubusercontent.com/assets/1583873/13720327/8e1e6a60-e840-11e5-8535-5d67b6fcf176.png)

**Comment by sreejakshetty** [comment]
@mariobehling 
I have included  elegant-icons.min.css but i am unable to view the images.
![screenshot from 2016-03-12 11 42 19](https://cloud.githubusercontent.com/assets/14835922/13721290/83bfdeb2-e847-11e5-9043-ad23bcb4c940.png)
Can you help me out

**Comment by sreejakshetty** [comment]
@mariobehling  Is this fine ?
![screenshot from 2016-03-12 15 16 59](https://cloud.githubusercontent.com/assets/14835922/13722266/8bd9c4a0-e865-11e5-930b-22090d318e16.png)

**Comment by jigyasa-grover** [comment]
- @kamishettysreeja25 In my opinion, they would look better if right aligned as shown in @mariobehling 's mockup
- Also, change the `GitHub` icon, use the Octocat one instead.

**Comment by joerx** [comment]
The event is approaching quickly and we are having less time for detailed discussions. Please just get to work and send a PR when done. We will give our feedback and merge when we're fine with the solution.

**Comment by jigyasa-grover** [comment]
@kamishettysreeja25 Working on this ?

**Comment by sreejakshetty** [comment]
@jig08 @joerx @SilentFlame 
I think we can directly add the social links using  elegant-icons.min.css as we have done for http://2016.fossasia.org/ i was trying for that instead of adding  the images for the social media

**Comment by SilentFlame** [comment]
@kamishettysreeja25  It just ran out of my mind, you can do that if you want to.

**Comment by sreejakshetty** [comment]
@SilentFlame 
I am not able to load the images it is showing blank for me , you can do it   if you are able to load the images from the bootstrap  :)

**Comment by aayusharora** [comment]
![socialicons added](https://cloud.githubusercontent.com/assets/12194719/13831964/ace7f428-ebfd-11e5-975d-f0eea51e34c1.PNG)
@mariobehling ,@joerx solved here #102.

**Comment by aayusharora** [comment]
@mariobehling , Kindly review.

**Comment by mariobehling** [comment]
@aayusharora Could you please help to follow up on this here at the OTS event https://github.com/OpenTechSummit/2016.opentechsummit.net/issues/3

**Comment by aayusharora** [comment]
@mariobehling , yeah sure .
