### ISSUE TITLE
Schedule: Add speakers and other info when expanding detail view

### ISSUE THREAD

**Issue by mariobehling** [fossasia/2016.fossasia.org#75]
At the moment only the info of the sessions is expanded. Please add the following on expansion:
- [ ] speakers info
- [ ] social media icons with link to website, github, twitter, linkedin

**Comment by rctay** [comment]
Rough cut: https://github.com/fossasia/open-event-scraper/pull/19

Need to add images/icons, alignment etc. I'll leave this to someone else.

**Comment by joerx** [comment]
Done
