### ISSUE TITLE
Schedule: Add speaker photos to speaker sessions

### ISSUE THREAD

**Issue by mariobehling** [fossasia/2016.fossasia.org#76]
![screenshot from 2016-03-12 23 22 43](https://cloud.githubusercontent.com/assets/1583873/13723779/20912f2c-e8aa-11e5-9529-b7f9c10c182e.png)

**Comment by aayusharora** [comment]
@mariobehling ,Is this also a change to be done  in open-event-scraper ?According to read me I should not do any change in Schedule section.
