### ISSUE TITLE
Schedule: Implement a simple search

### ISSUE THREAD

**Issue by mariobehling** [fossasia/2016.fossasia.org#77]
![screenshot from 2016-03-13 00 30 53](https://cloud.githubusercontent.com/assets/1583873/13724037/32b05800-e8b3-11e5-9ac5-02167b59a3f4.png)

**Comment by joerx** [comment]
It's a static page. Why not just use the built-in search of the browser?

**Comment by mariobehling** [comment]
... it is difficult to handle on mobile. Search could show e.g. all talks of a speaker.

**Comment by aayusharora** [comment]
@mariobehling ,@joerx I am almost done with it

**Comment by aayusharora** [comment]
@mariobehling ,@joerx solved here  #85
