### ISSUE TITLE
Schedule: Get a link to sessions, that can be shared?

### ISSUE THREAD

**Issue by mariobehling** [fossasia/2016.fossasia.org#93]
Best would be to get a link with the session ID, so the link stays in case the session is moved.

**Comment by anas24** [comment]
@mariobehling How to start working to remove this issue

**Comment by mariobehling** [comment]
Hi, this is a basic solution, that works, but the anchor is really distracting. Please move the anchor into the expandable bottom section and make it into a "share link".

Step one: User can see and click on the share link. Please see bottom right

![screenshot from 2016-03-16 08 44 41](https://cloud.githubusercontent.com/assets/1583873/13798750/38fc04d6-eb54-11e5-8ada-22891483f1e0.png)

Step two: User clicks on the link and an area with the real link, that can be copied is displayed.

![screenshot from 2016-03-16 08 44 41-1](https://cloud.githubusercontent.com/assets/1583873/13798771/5574bc70-eb54-11e5-9e69-a1b9594cfef8.png)
