### ISSUE TITLE
Add a "Sign up" link for workshop or other sessions that need an additional sign up

### ISSUE THREAD

**Issue by mariobehling** [fossasia/2016.fossasia.org#98]
The page can have a column "sign up" that redirects to meetup or other services where people could sign up. (The data column or JSON data needs to have the option "Sign up")

![screenshot from 2016-03-16 19 08 51](https://cloud.githubusercontent.com/assets/1583873/13810431/c4b299b2-ebaa-11e5-81bb-9c98c2ab6421.png)

**Comment by SilentFlame** [comment]
@mariobehling and where should it redirects?
I mean do we have any portal or anything for signup till?

**Comment by mariobehling** [comment]
Done.
